name: Contexts
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{github.event.pull_request.title}}"
            - run: echo "echo debug info ${{runner.debug}}"